- src/Actions/Delete.ts
- src/Actions/Insert.ts
- src/Actions/JoinLines.ts
- src/Actions/Replace.ts
- src/Actions/Reveal.ts
- src/Modes/Insert.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
Passing method directly to then will cause unexpected params getting passed.
> `then` refactoring

- package.json
- src/Actions/Page.ts
- src/Actions/Selection.ts
- src/Keys.ts
- src/Mappers/SpecialKeys/Motion.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
- src/Motions/Document.ts
Address #29.
`N` is not supported.
> Support `ctrl+f` and `ctrl+b`

- src/Mappers/SpecialKeys/Motion.ts
- src/Motions/Word.ts
- test/MotionWord.test.ts
Adds suport for WORD-motions "W", "E" and "B".
Incorporates comments from #67
> Added new Motions "W", "E", "B"

- src/TextObjects/QuotedString.ts
> ignore escaped quote-characters resolves #74

- src/Actions/Delete.ts
- src/Configuration.ts
- src/Mappers/SpecialKeys/Motion.ts
- src/Modes/Normal.ts
- src/Motions/Word.ts
- test/MotionWord.test.ts
- test/Util.ts
- Respect user settings.
- Move across lines.
- #52
- #65
> Refactoring word motions

- src/Actions/Find.ts
- src/Actions/Selection.ts
- src/Dispatcher.ts
- src/Modes/Normal.ts
- src/extension.ts
> Validate selections when changed.

- src/Actions/Mode.ts
- src/Modes/Insert.ts
> Validate selections when exiting insert mode

- src/Mappers/SpecialKeys/Motion.ts
- src/Motions/MatchPair.ts
- src/TextObjects/Block.ts
- src/TextObjects/QuotedString.ts
- src/TextObjects/TextObject.ts
fixes #80 
This is my biggest pull request yet.
It was pretty easy to implement, because I could reuse a lot of the existing code.
Below are some/comments question to some specific parts.
> implemented '%' for matching pairs of '{[()]}'

- package.json
- src/Keys.ts
- src/Modes/Insert.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
> ctrl-[ to exit insert mode

- src/Actions/Insert.ts
- src/Modes/Insert.ts
> Fix Chinese input through IME

- src/Mappers/Generic.ts
- src/Modes/Mode.ts
- src/Motions/Motion.ts
- test/MotionIntegration.test.ts
- test/Util.ts
- test/extension.test.ts
> Bug in `GenericMapper.match` when there are multiple input commands at once

- src/Configuration.ts
- src/Mappers/SpecialKeys/TextObject.ts
- src/Motions/Word.ts
- src/TextObjects/TextObject.ts
- src/TextObjects/Word.ts
- src/Utils/Word.ts
- test/TextObjects/Word.test.ts
- test/extension.test.ts
> Support for Word TextObjects "ciw", "caw", "diw", "daw"

- src/Actions/Selection.ts
- src/Modes/Visual.ts
- test/Actions/Selection.test.ts
- test/extension.test.ts
This adds support for things like `viw`, `vi'`, `vi[`
> Adds support for visual selection by text object.

- src/Actions/BlockCursor.ts
- src/Actions/Delete.ts
- src/Actions/Register.ts
- src/Motions/Character.ts
- src/Motions/Document.ts
- src/Motions/Motion.ts
- src/Motions/Word.ts
- test/Actions/Delete.test.ts
- test/Motions/Word.test.ts
- test/Util.ts
- test/extension.test.ts
> Fix motion bugs around line breaks

- src/Actions/Selection.ts
- src/Modes/Insert.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
- src/Utils/Selection.ts
> Better selections shrinking behavior.

- src/Actions/Fold.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
Support following commands
* `z o`
* `z c`
* `z M`
* `z R`
> add folding command

- src/Actions/Register.ts
- src/Actions/Replace.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
This adds `p` and `P` support in Visual and VisualLine modes.
Address #139.
> `p` support in Visual and VisualLine modes

- src/Actions/Case.ts
- src/Actions/Delete.ts
- src/Actions/Register.ts
- src/Actions/Replace.ts
- src/Modes/VisualLine.ts
- src/Motions/Line.ts
- src/TextObjects/Block.ts
- src/TextObjects/TextObject.ts
- src/Utils/Range.ts
- src/Utils/Selection.ts
- src/Utils/Text.ts
- test/ModeVisualLine/p.test.ts
Fixes wrong behavior around yank and paste.
Fixes #150, #151, #36.
- ~~Multi-register support.~~ Will do this in another p-r.
> Better register handling

- src/Actions/Mode.ts
- src/Modes/Insert.ts
- test/ModeInsert/escape.test.ts
- test/ModeNormal/d a {.test.ts
> Fix curosr position when exiting insert mode

- src/Actions/Indent.ts
- src/Dispatcher.ts
- src/Modes/Mode.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
- src/Types/RangeOffset.ts
- src/Utils/Range.ts
- src/Utils/Text.ts
- test/Framework/BlackBox.ts
- test/Framework/Util.ts
- test/ModeVisual/<.test.ts
- test/ModeVisual/>.test.ts
- test/ModeVisual/repeat.test.ts
Address #108.
Also adds support to repeat Visual and VisualLine mode's command.
> Repeat command in Visual and VisualLine mode

- src/Actions/Insert.ts
- src/Dispatcher.ts
- src/Modes/Insert.ts
- src/Modes/Mode.ts
> Support repeat of deletion and autocomplete in Insert mode

- src/Actions/MoveCursor.ts
- src/Motions/MatchPair.ts
- src/Motions/Word.ts
- src/Utils/Selection.ts
- test/ModeNormal/~.test.ts
- test/ModeVisual/h.test.ts
- test/ModeVisual/l.test.ts
Fixes #171 .
Also contains minor fix with motions in Visual mode.
> Fix wrong behavior with %

- src/Actions/Register.ts
- src/Dispatcher.ts
- src/Mappers/SpecialKeys/Motion.ts
- src/Modes/Mode.ts
- src/Modes/Normal.ts
- src/Motions/Direction.ts
- src/Motions/Paragraph.ts
- src/Motions/Word.ts
- test/ModeNormal/{.test.ts
- test/ModeNormal/}.test.ts
> Support paragraph motions `{`, `}`

- src/Actions/Command.ts
- src/Actions/Fold.ts
- src/Modes/Normal.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
Address #190.
Press `:` in Normal mode to active Go To Line widget.
> Add go to line command

- README.md
- package.json
- src/Configuration.ts
> Added Vim style navigation in sidebar

- src/Actions/Indent.ts
- src/Modes/Visual.ts
- src/Modes/VisualLine.ts
- test/ModeVisual/Y.test.ts
- test/ModeVisualLine/Y.test.ts
> `Y` in Visual and VisualLine modes

- src/Modes/Normal.ts
- test/ModeNormal/d {N} {motion}.test.ts
- test/ModeNormal/{N} d {motion}.test.ts
> Supports {N} d {motion}

- src/Actions/Delete.ts
- src/Modes/Normal.ts
- test/ModeNormal/{N} x.test.ts
`{N} x` and `{N} X` seem to work the way I expect them to.
I haven't touched the `args.isMultiline === true` path of `selectionsOrLeft` or `selectionsOrRight` because I don't really see where/how they're being used. Maybe you could give me a hint?
> Feature/n x and n X

- src/Actions/JoinLines.ts
- test/ModeNormal/J.test.ts
- test/ModeVisual/J.test.ts
I think this fixes #179. What do you think @aioutecism?
If it's okay, I'll write some tests before you merge.
> fix join lines

- src/Mappers/SpecialKeys/Motion.ts
- src/Motions/Empty.ts
- src/Motions/Match.ts
- test/ModeNormal/comma.test.ts
- test/ModeNormal/semicolon.test.ts
> Adding support for `;` and `,`

- src/Actions/RelativeLineNumbers.ts
If it's `"off"`, don't do anything.
For #214.
I think this is the right approach but I'm still new to vscode extensions so happy to  take any feedback :)
> Respect `editor.lineNumbers`

- README.md
- package.json
- src/Configuration.ts
> Add `amVim.mimicVimSearchBehavior` configuration

- src/Actions/Commands/GoToLine.ts
- src/Mappers/SpecialKeys/Motion.ts
- src/Motions/Document.ts
Hi!
I liked your extension and decided to contribute a bit to help get through your roadmap faster. I'm just starting with TypeScript, so something simple for the beginning: motion to given percent of source code.
> Go to percent in file

- src/Modes/Normal.ts
- test/ModeNormal/{N} ~.test.ts
Switch case for N chars and move cursor
> Implement `{N} ~` for normal mode

- README.md
The new links and the protip helped me &ndash; hopefully they'll be useful to new contributors as well.
I also moved the link definitions to the end of the Contributing section to make the text clearer.
> Update readme with more contribution instructions

- README.md
> Document system clipboard option

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- .vscodeignore
- package-lock.json
- package.json
- src/extension.ts
- test/Framework/BlackBox.ts
- test/runTest.ts
- webpack.config.js
Hey, I was looking at my Running Extensions list on my vscode and notice that amVim startup time is around ~50ms and noticed that it doesn't bundle the extension as recommended here https://code.visualstudio.com/api/working-with-extensions/bundling-extension
This PR does exactly that, bunding the extension using webpack.
From my test in my local, the average startup time of amVim went down from average ~50ms to ~10ms
before:
after:
> Bundle with Webpack

- test/runTest.ts
Mini follow-up to #270 to make sure our lint check passes.
> fix indentation in runTest

- .github/workflows/test.yml
- package-lock.json
Upgrade to new `setup-node` action and latest LTS Node 14.
> bump to node 14 lts and npm audit fix

- .github/workflows/test.yml
Latest is v1.4, this will allow CI to track it.
> use latest xvfb-action to test

- .github/workflows/test.yml
Some more housekeeping. `GabrielBB/xvfb-action` isn't ready yet: https://github.com/GabrielBB/xvfb-action/issues/30
> bump github actions to node 16

- README.md
Add documentation for the waiting for input context introduced in #303.
> document supported key binding contexts
