aioutecism/amVim-for-VSCode

src/Dispatcher.ts, src/Modes/Insert.ts
`recordedCommandMaps` should only apply when we switch from insert mode.
for example try this key sequence starting in `Normal` Mode
`i12345<esc>V<esc>.`
you will see that `12345` is printed multiple times. this pr fixes this issue.
=> fix logic for recordedCommandMaps when swithing from Insert Mode

src/Actions/BlockCursor.ts
This uses Bock cursor style form vscode new api for Normal mode.
I tried to use the same for Vitual Mode, but vscode Ranges are not inclusive and if we use cursor block style the character that is behind the cursor is not selected.
=> Use TextEditorCursorStyle.Block for Normal mode.

src/Mappers/Generic.ts, src/Modes/Mode.ts, test/MotionIntegration.test.ts, test/Util.ts, test/extension.test.ts
This bug is hard to explain in words. So I created this pull-request to illustrate it with code.
I was playing around with some tests to understand the code better. I was "simulating" input in my tests. See the `MotionIntegrationTest`.
The test did not behave as expected. 
Then I did some debugging. The debugging showed that in `Mode` the `map` objects did seem to somehow get overwritten when multiple maps are in the `this.pendings` array.
When there where more than one map-object in `this.pendings` they were essentially the same map object (`this.pendings[0] === this.pendings[1]`)
The added code in Generic.ts fixes seems to fix this problem. Although I am not 100% sure why I have to do this.
So this pull-request is not a complete solution to the problem.
I hope I can help you find the …
=> Bug in `GenericMapper.match` when there are multiple input commands at once

src/Actions/BlockCursor.ts, src/Actions/Filter.ts, src/Modes/Normal.ts, src/Modes/Visual.ts, src/Modes/VisualLine.ts
Uses VSCode's built in formating command to format selections.
`{N} = =` is not supported yet.
Solves #126 .
=> Semi support for `=` filter

src/Modes/Visual.ts, src/Modes/VisualLine.ts
`{visual}u` and `{visual}U` are used for transforming selected text to lowercase and uppercase.
I tweaked `{visual}~` to behave similarly than in vim, i.e. that after the operation the selection is deselected. `{visual}u` and `{visual}U` behave that way as well.
(Side note: I noticed that `{visual}~` doesn't work with special characters, e.g. å, ä and ö.)
=> Implement {visual}u and {visual}U, tweak {visual}~

src/Utils/Text.ts
As I mentioned in #169, `{visual}~` doesn't work with special letters. This should fix it.
=> Fix {visual}~ to work with special characters

src/Actions/Delete.ts, src/Actions/Register.ts, src/Mappers/Generic.ts, src/Mappers/SpecialKeys/Char.ts, src/Mappers/SpecialKeys/Common.ts, src/Mappers/SpecialKeys/Motion.ts, src/Mappers/SpecialKeys/N.ts, src/Mappers/SpecialKeys/TextObject.ts, src/Modes/Normal.ts, src/Modes/Visual.ts, src/Modes/VisualLine.ts, src/Motions/Document.ts, test/ModeNormal/d {N} d.test.ts, test/ModeNormal/y y.test.ts, test/ModeNormal/y {N} y.test.ts, test/ModeNormal/{N} d d.test.ts, test/ModeNormal/{N} p.test.ts, test/ModeNormal/{N} y y.test.ts
This addresses:
- #128 
- #26
- #25
- #20 
Added support for:
- `Ndd`, `dNd`
- `Nyy`, `yNy`
- `Np`, `NP`
Other commands support for `N` will be added in separate pull requests.
=> Support for N before commands

package.json
When switching branches, tests in the `out` directory from a previous branch which don't exist the current branch will fail.
This PR deletes the `out` directory using `rimraf` before compiling.
=> (chore) added clean npm script

src/Actions/Find.ts
Seems like `action.focusActiveEditor` command has been removed with VSCode 1.25.0
I've found a `workbench.action.focusActiveEditorGroup` it seems to do the same thing and it work against newest version.
=> Find.ts us workbench.action.focusActiveEditorGroup instead of search action.focusActiveEditor

src/Modes/Normal.ts
There's further work here to support some equivalent of Vim's
`scrolloff` (see
https://stackoverflow.com/questions/26915320/vim-zt-will-redraw-the-window-with-the-cursor-at-the-top-can-you-redraw-with)
but I was missing using `zt` and it tunrs out to be an easy addition :)
Happy to follow up with a config option like `amVim.scrollOff` and support it for `zt` if you think that's useful?
=> Add `zt` to put cursor at top of screen

README.md
[VS Code's documentation](https://code.visualstudio.com/docs) abbreviates "Visual Studio Code" as "VS Code" instead of "VSCode" 🙃
=> Rename "VSCode" to "VS Code" in readme

package.json
This means that when using VSCode Remote amVim will not be installed
remotely and will run on the machine, not the remote server. This keeps
it snappier as commands don't have to be run through the server.
See https://code.visualstudio.com/api/advanced-topics/remote-extensions#common-problems
=> Mark extension as UI, not workspace

src/Actions/Navigation.ts, src/Modes/Normal.ts
This PR adds support for the `gd` and `gD` commands in a way that I think makes sense in the context of VS Code.
In vim, `gd` seems to search up through the current code block to where it thinks the current identifier (variable/function) might have been defined. With this change, amVim will have the same effect, although it will also jump into a different file if the identifier you are on is defined elsewhere. This is the same action that happens in VS Code when you Ctrl-Click.
In vim, `gD` seems to search down from line 0 to where it thinks the current identifier (variable/function) might have been defined as a global. With this change, amVim will jump to the type definition of the current identifier (even if it is in a different file). This does nothing in languages without type …
=> add `gd` and `gD` to go to declaration and type definition

package-lock.json, package.json, src/LanguageExtensions/StaticReflect.ts, test/index.ts, test/runTest.ts
This ticket combines a commit from #258 to upgrade the test dependencies to new vscode-test, and the work from #217 to upgrade to a newer version of TypeScript. I have also made sure that package.json includes the latest dependencies from the lock file, as generated by our Node 8.6 and NPM 5.6 build environment.
Note: Node and NPM are not update here, just the dev dependencies.
=> Upgrade dependencies (TypeScript, vscode-test)

package.json
Since the requirement inside `engines` block impacts which versions of VS Code can install the extension, it seems fair to set it back to an older version so people can upgrade the extension even if they didn't upgrade VS Code itself.
The number is pretty arbitrary - 1.32.0 is the same version used in Microsoft's Hello World extension (https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample/package.json), which is the structure I based the test script changes on for #259.
=> revert the vscode api requirement to 1.32.0

package.json, src/Actions/Action.ts, src/Actions/Register.ts, src/Configuration.ts
Okay, my first try to implement this feature of copying to and pasting from the system clipboard!
Not sure if this is what you meant @aioutecism. Happy to take feedback and improve this still!
I tried changing from `Thenable` to `Promise` to allow for `async` methods on `putAfter` and `putBefore` so that there's not this `.then()` callback hell, but I guess async methods are not supported? Anyway, would love to do this a better way if possible.
This will not overwrite the stash register in case:
1. there is nothing returned from the system clipboard promise  OR...
2. what is in the system clipboard is already in the existing stash
Closes #17
Closes #166
=> Copy to and paste from system clipboard

package-lock.json, package.json
Update: as discussed in comments (below) we are removing node and npm from the `engines` block, since we do not use any features from a particular version, and anyway VS Code does not mandate it. I would suggest contributors use the latest LTS, although for now we will stick with Node 8.x Typescript hints.
~This PR brings us to the latest Node 8.x and its packaged npm. I think most developers were already running this, but now I have updated the package.json to reflect it and regenerated the lock file. I think this will help to create more reproducible builds. This is also the same version the default Github actions setup for Node is using.~
=> remove node and npm from engines

src/Actions/Delete.ts, src/Actions/MoveCursor.ts, src/Actions/Register.ts, src/Mappers/SpecialKeys/Motion.ts, src/Motions/Direction.ts, src/Motions/Document.ts, src/Motions/Line.ts, src/Motions/Match.ts, src/Motions/MatchPair.ts, src/Motions/Motion.ts, src/Motions/Navigation.ts, src/Motions/Paragraph.ts, src/Motions/Word.ts, test/Framework/BlackBox.ts, test/Framework/Util.ts, test/ModeNormal/g d.test.ts, test/index.ts
This is a new attempt to add the VS Code "go to definition" command as the `gd` amVim motion.
In the previous approach (#250) i implemented the command as a top-level amVim action, but this caused problems because it hijacked the matching of motions that already existed, such as `gg`. I looked at several ways to solve this, but i think the most vim-like was to respect the concept of `gd` as a motion, so that's what i have attempted here.
It required three steps:
1. **Change the `Motion.apply` function to be async (i.e. return a promise).**
This was required because in order to make motions able to execute VS Code commands, they need to be able to wait for the `Thenable<boolean>` to resolve. This problem was also encountered by @Ddedalus in #230, so adding this functionality should also …
=> Add `gd` go to definition motion

package.json
Hi! Thanks for making this awesome extension.
Recently I found the extension doesn't work in remote development, such as [GitHub Codespaces](https://github.com/codespaces):
> VSCode:
> Error while installing 'amVim' extension.
> Cannot install 'amVim' because this extension has defined that it cannot run on the remote server.
---
According to the document from VSCode, it seems like the current value (`ui`) of `extensionKind` required too much access in this case. 
> "extensionKind": ["ui"] — Indicates the extension must run as a UI extension because it requires access to local assets, devices, or capabilities. Therefore, it can only run in VS Code's local extension host and will not work in the Codespaces browser-based editor (as there is no local extension host available).
> …
=> feat: support remote development mode with workspace execution location

src/Actions/Find.ts
When searching, Vim always puts the cursor at position 0 of the matched string, then when you hit `n` it will start searching one
character to the right for the next match. VS Code always starts searching from the current position. So we hack Vim-like behavior by nudging the cursor one to the right before searching, then if we do not find any matches, we nudge it back to the left. This causes a bit of cursor jumpiness when there are no matches, but it should resolve #261.
We can't test this easily using the integration tests, but you can manual test like this.
Given you are in normal mode, and the document has text `foo foo foo`,
When you type `/oo<RET>rrn.n.`,
Then you will get `fro fro fro`.
=> fix behavior of next match (n) by nudging the cursor

src/Actions/Mode.ts, src/Actions/Replace.ts, src/Actions/Selection.ts, src/Dispatcher.ts, src/Modes/Insert.ts, src/Modes/Mode.ts, src/Modes/Normal.ts, src/Modes/Replace.ts, test/ModeNormal/r.test.ts
This PR has some small improvements for replace command (`r`).
1. Allow replace multiple characters, e.g. `5rt` will replace 5 characters with `t`
2. Fix bug in visual mode where replace over the newline boundary would replace also the invisible carriage return character
3. Add integration test for replace command
I also added a basic version of replace mode (`R`), to resolve #243.
The initial version is a fairly simple implementation - it is essentially a subclass of insert mode, so all behaviors are identical, except just before inserting the text it expands the selection one character forwards. This handles the situation of a user just hitting `R` and starting to type normally in overwrite/replace mode. What does not quite work is:
1. Paste inside replace mode inserts from clipboard, …
=> improve replace command (r) and add basic replace mode (R)

.vscode/launch.json, package.json, src/Mappers/SpecialKeys/Motion.ts, src/Motions/WrappedLine.ts
This is a basic implementation of the motions `g 0`, `g $`, `g j` and `j k` to navigate around with wrapped lines. See #116.
Due to the way VS Code works, we have to jump the cursor around a little bit to plan the motion before we actually execute it, which causes some unfortunate flickering, but at least the functionality is there if you need it. I wasn't easily able to add tests for this because I'm still not sure how to set up the test VS Code instance with non-default settings for line wrap.
There are a couple of known issues:
1. Visual mode sometimes switches mysteriously between one character to the left and one character to the right of where you expect it to be, specifically when you cross over the starting point of your visual selection.
2. VS Code does not remember what column …
=> Wrapped line support

src/Mappers/SpecialKeys/Motion.ts, src/Motions/WrappedLine.ts
I haven't really been able to figure out how `g^` behaves differently from `g0` in my testing, but it's harmless to add. `gm` is more useful.
=> add g^ and gm

src/Modes/Mode.ts
This PR adds a [custom when clause context](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context) to check if amVim is waiting for input. For example, `g` is an incomplete input, waiting for another keystroke, e.g. another `g` (so the complete input would be `g g`).
This allows specifying more powerful keyboard shortcuts in VS Code. For example, both #21 and #184 would be fixed (at least partially) with this PR and the following keyboard shortcuts:
```json
[
{
"key": "j",
"command": "cursorMove",
"when": "editorTextFocus && amVim.mode == 'NORMAL' && !amVim.waitingForInput",
"args": { "to": "down", "by": "wrappedLine" }
},
{
"key": "k",
"command": "cursorMove",
"when": "editorTextFocus && amVim.mode == 'NORMAL' && !amVim.waitingForInput", …
```
=> Add a custom "when clause context" for "waiting for input"

src/Actions/MoveCursor.ts, src/Dispatcher.ts, src/Modes/Insert.ts, src/Modes/Mode.ts, src/Modes/Normal.ts, src/Modes/Visual.ts, src/Modes/VisualLine.ts
This is small clean-up pull request which removes some functions that were unnecessarily declared to return promise/thenable and also adds a couple of await when we respond to selection or tab change events from the VS Code window. It's possible that this will solve #308, but since I can't reproduce it, I can't be certain.
There is a more ambitious change that would involve making the core `execute` function of each mode async and awaiting it in the input handler, but I suspect that might make the extension feel a bit laggy, so I'd rather not do that unless we're sure it's going to make a difference.
=> Await mode changes

.github/workflows/test.yml
The [GabrielBB/xvfb-action](https://github.com/GabrielBB/xvfb-action) that we use for testing is using the deprecated Node 12 base image and appears to be unmaintained. Since the `ubuntu-latest` image now includes `xvfb-run`, we can replace this image with a conditional step to use `xvfb-run` on Linux and just build straight on Windows/Mac.
=> replace xvfb-action with xvfb-run

test/Framework/BlackBox.ts
Just a small change to make the test failures easier to understand.
=> un-mangle the typescript so assert output is more readable

.vscode-test.mjs, package-lock.json, package.json, src/Dispatcher.ts
Bump vscode engine to 1.75.0 and attempt to address the test flakiness and the "cursor in the wrong position" bug reported in #308 and #317.
=> Fix 1.75 flakiness
